### ISSUE TITLE
Staged EL TCK contains reference to unavailable SNAPSHOT version of parent

### ISSUE THREAD

**Issue by markt-asf** [jakartaee/platform-tck#1298] opened 2024-05-08 14:04 UTC
**Describe the bug**
The EL 6.0.0 TCK staged at https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee11/staged/eftl/ contains a reference (under META-INF/maven) to version 10.0.0-SNAPSHOT of its parent POM. There are two issues:
- a released version of the TCK should not depend on a SNAPSHOT
- the SNAPSHOT version is not available in the snapshot repository

**To Reproduce**
1. Download the zip
2. Extract the TCK JAR
3. Use the Maven install plugin to add the JAR to your local repository
4. Try and use the TCK JAR

**Expected behavior**
Maven shoudl be able to resolve all of the dependencies of this JAR without using snapshots.

**Additional context**
It can be worked around by changing the reference to jakarta.tck:project:11.0.0-M1 in the pom file generated for this JAR in your local Maven repository.

**Comment by brideck** [comment] 2024-05-22 15:21
It should be noted that this bug is also present in the official release of the TCK at https://download.eclipse.org/jakartaee/expression-language/6.0/jakarta-expression-language-tck-6.0.0.zip

Open Liberty would appreciate this being fixed in a formal 6.0.x release, as it's a silly bug to have to work around to get things running out of the box.

**Comment by alwin-joseph** [comment] 2024-07-05 06:14
> It should be noted that this bug is also present in the official release of the TCK at https://download.eclipse.org/jakartaee/expression-language/6.0/jakarta-expression-language-tck-6.0.0.zip
> 
> Open Liberty would appreciate this being fixed in a formal 6.0.x release, as it's a silly bug to have to work around to get things running out of the box.

I have staged https://www.eclipse.org/downloads/download.php?file=/ee4j/jakartaee-tck/jakartaee11/staged/eftl/jakarta-expression-language-tck-6.0.1.zip. Can you verify this bundle once so it can be released to official location.

**Comment by brideck** [comment] 2024-07-17 19:52
> I have staged https://www.eclipse.org/downloads/download.php?file=/ee4j/jakartaee-tck/jakartaee11/staged/eftl/jakarta-expression-language-tck-6.0.1.zip. Can you verify this bundle once so it can be released to official location.

Sorry, I missed this comment when it was first posted. I can confirm that the staged 6.0.1 EL TCK resolves this issue to our satisfaction with Open Liberty. Presumably @markt-asf would feel the same way?

**Comment by markt-asf** [comment] 2024-07-17 21:24
I'm happy if @brideck is happy

**Comment by markt-asf** [comment] 2024-07-20 09:36
Sorry, scratch that. 6.0.1 appears to be broken.

I'm not 100% certain as I can't figure out how the 6.0.1 EL TCK was built. If someone could point me to the tag that was used that would help. I'm not even sure which branch it was created from.

What I can tell is that 6.0.1 depends on sigtest-maven-plugin which has changed the syntax for the IgnoreJDKClass option. 6.0.1 still uses the old syntax which means that the signature test fails. Forcing the sigtest-maven-plugin dependency back to 2.2 fixes the problem.

**Comment by scottmarlow** [comment] 2024-07-20 10:13
I will take a look today.

I have a pending change to fix the sig test compatibility with the ignore
option (old syntax should work and new way also).

**Comment by scottmarlow** [comment] 2024-07-20 12:31
http://download.eclipse.org/ee4j/jakartaee-tck/jakartaee11/staged/eftl/ has updated https://www.eclipse.org/downloads/download.php?file=/ee4j/jakartaee-tck/jakartaee11/staged/eftl/jakarta-expression-language-tck-6.0.1.zip 

https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee11/staged/eftl/jakarta-expression-language-tck-6.0.1-tckinfo.txt contents:
> ***********************************************************************************
> ***                        TCK bundle information                               ***
> *** Name:       jakarta-expression-language-tck-6.0.1.zip                                     ***
> *** Bundle Copied to URL:    http://download.eclipse.org/ee4j/jakartaee-tck/jakartaee11/staged/eftl//jakarta-expression-language-tck-6.0.1.zip ***
> *** Date and size: date: 2024-07-20 12:26:16.168503608 +0000, size(b): 543923        ***
> *** SHA256SUM: 8ca4339e1b93c8f490c38b5888d8a54d09f7d12257b222bff2d44d665f323cee ***
> ***                                                                             ***
***********************************************************************************

Please let me know if the signature tests work now for you.  As well as any other problems.  I'll push a tag if all tests pass for you.

**Comment by markt-asf** [comment] 2024-07-20 18:47
Tx for the quick response. All looks good now. EL 6.0.1 TCK passes with current Tomcat 11.0.x source.

**Comment by scottmarlow** [comment] 2024-07-20 19:01
Tag for this staged build is https://github.com/jakartaee/platform-tck/releases/tag/expression-language-tck-6.0.1.zip

**Comment by alwin-joseph** [comment] 2024-07-22 06:26
Thanks Scott for the fix! I created PR https://github.com/jakartaee/specifications/pull/768 to release the TCK bundle.

**Comment by brideck** [comment] 2024-07-31 13:51
Not sure if you're waiting for me at all, but it looks like I need to make a quick update on my end to handle the follow-on sigtest update. Should be able to give this the all clear by the end of today.

**Comment by brideck** [comment] 2024-07-31 14:54
All right, that didn't take nearly as long as I thought it might. The more recent staged 6.0.1 release looks good on my end as well.

**Closed** 2024-08-21 05:30 UTC
Labels: 11.0
